#!/bin/bash
while read line
do
	name=$line
	echo "$name"
	curl -O "ftp://ftp2.census.gov:21/geo/tiger/TIGER2013/ROADS/"$name".zip"
	unzip $name.zip
	shp2pgsql -I -s 4326 -W "latin1" $name.shp $name | psql -d dbtiger
	rm $name.shp
	rm $name.dbf
	rm $name.prj
	rm $name.shx
	rm $name.shp.xml
	rm $name.zip
done < $1
